### ISSUE TITLE
Re: Not quite sure how to only fire when Gmail updates the interface / inserts new divs

### ISSUE THREAD

**Issue by ghost** [gserafini/fix-gmail-email-search-userscript#1]
Did you try using onElementReady or monkey-in-zoo?

https://greasyfork.org/en/scripts/374849-library-onelementready-es6

https://github.com/Cologler/monkey-in-zoo-javascript

**Comment by gserafini** [comment]
Hi @ghost, I haven't tried those, but I'll take a look at them and see if it improves performance at all (although for me it's good enough currently, even though there's a slight delay for the search icon to show up).

**Comment by gserafini** [comment]
Looking further at both of those libraries it looks like neither would really improve how I'm doing it currently (just waiting and re-polling periodically for the elements).  Thanks for the feedback and ideas!
