### ISSUE TITLE
Magnifying glass(search Icon) missing from hovercards displayed in the inbox

### ISSUE THREAD

**Issue by efighter** [gserafini/fix-gmail-email-search-userscript#3]
This functionality changed in late 2020 when the GMail markup changed.   The hovercard no longer has a magnifying glass icon when displayed from the inbox.

**Comment by efighter** [comment]
![image](https://user-images.githubusercontent.com/19535912/133719329-f55d83e3-1d69-4a81-9dcb-e2cd0ed43dd7.png)

**Comment by gserafini** [comment]
I've noticed that as well... they changed something about how those hovercards are served up.  Will try to get the previous functionality back if possible :)

**Comment by gserafini** [comment]
This now works again (something they did on the backend reverted).
