### ISSUE TITLE
Magnifying Glass Icon fails to insert from within EMail and from List of Email

### ISSUE THREAD

**Issue by efighter** [gserafini/fix-gmail-email-search-userscript#8]
since January the icon was only appearing within an Email.  However the Markup has changed and the icon no longer appears at all anywhere within GMail.

**Comment by gserafini** [comment]
Try adding this script (https://github.com/tophf/trust-any-html) to your Tampermonkey install (set it as the first script to execute, and include the following sites into the top comments (this is what controls where this executes):

// @match        *://mail.google.com/*
// @match        *://contacts.google.com/widget/hovercard/*
// @match        *://gmail.com/*
// @match        *gmail.com/*
// @match        *mail.google.com/*
// @match        *contacts.google.com/widget/hovercard/*

**Comment by tonylost** [comment]
Thank you for your assistance! I added (https://github.com/tophf/trust-any-html) as first script to execute, but adding asterisks in the values "@match" you've specified, and now the magnifying glass icon is displaying again. 

The new values are:

// @match        *://mail.google.com/*
// @match        *://contacts.google.com/widget/hovercard/*
// @match        *://gmail.com/*
// @match        *gmail.com/*
// @match        *mail.google.com/*
// @match        *contacts.google.com/widget/hovercard/*

I hope this helps other users as well!

**Comment by gserafini** [comment]
Glad that worked! 

I wish Gmail would just incorporate this functionality directly instead of us having to work around everything.

**Comment by archon810** [comment]
> set it as the first script to execute

How do you do this? Tampermonkey doesn't seem to include functionality to reorder script execution. I added the match strings to the Trust Any script, reloaded Gmail, but it didn't work, which I can only assume is due to the order of execution.

![image](https://github.com/gserafini/fix-gmail-email-search-userscript/assets/469543/a0180dfc-03b2-407b-ad58-78c53a402d01)

**Comment by archon810** [comment]
I uninstalled your script and reinstalled it, and Gmail still isn't showing the icon...
![image](https://github.com/gserafini/fix-gmail-email-search-userscript/assets/469543/deecde72-e16a-49ce-b261-2bc5168e3719)

![image](https://github.com/gserafini/fix-gmail-email-search-userscript/assets/469543/9fd8275f-27ac-4fb5-b1d0-b1f9a9360b89)


Edit: It's still complaining about TrustedHTML.

```
userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:3 
        
       Uncaught (in promise) TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:3:38037
    at userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:3:220
    at Object.<anonymous> (userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:3:225)
    at wt (<anonymous>:9:89)
    at userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:1:90
    at window.__f__lwiofhr9.oxc (userscript.html?name=Fix-Gmail-Email-Search.user.js&id=9dafd19c-761c-49a5-bae9-1a1a9f26a900:1:326)
    at wt (<anonymous>:9:89)
    at o (<anonymous>:80:114)
    at <anonymous>:82:497
    at v (<anonymous>:77:102)
```

**Comment by archon810** [comment]
I ended up finding this that does work https://gist.github.com/szhu/1d816086307c5de02bc9a2bb1cf01fe0 (you tap the sender, it doesn't add any icons). Maybe you can figure out how to make your script work properly without other dependencies based on this code.

**Comment by efighter** [comment]
@tonylost  or @gserafini  could one of you post the actual script text?  it appears that the project located (https://github.com/tophf/trust-any-html) here has been removed.  trying to get this running on a new PC.  Thanks

**Comment by tonylost** [comment]
> [@tonylost](https://github.com/tonylost) or [@gserafini](https://github.com/gserafini) could one of you post the actual script text? it appears that the project located (https://github.com/tophf/trust-any-html) here has been removed. trying to get this running on a new PC. Thanks

Here "Circumvent trustedTypes for HTML" by [tophf]
#Reuses the site's trustedHTML.createHTML policy for innerHTML assignments and insertAdjacentHTML
(https://github.com/tophf/)
https://web.archive.org/web/20240812071131/https://github.com/tophf/trust-any-html

```
// ==UserScript==
// @name        Circumvent trustedTypes for HTML
// @author      tophf
// @namespace   Violentmonkey Scripts
// @version     0.1.0.8
// @description Reuses the site's trustedHTML.createHTML policy for innerHTML assignments and insertAdjacentHTML.
// @match       ://mail.google.com/
// @match       ://contacts.google.com/widget/hovercard/
// @match       ://gmail.com/
// @match       gmail.com/
// @match       mail.google.com/
// @match       contacts.google.com/widget/hovercard/
// @grant       none
// @run-at      document-start
// ==/UserScript==
{
  const CP = 'createPolicy';
  const createPolicy = trustedTypes[CP];
  let createHTML;
  trustedTypes[CP] = function ovr(name, opts) {
    const p = createPolicy.call(trustedTypes, name, opts);
    if (!createHTML && (createHTML = p.createHTML)) {
      const el = document.documentElement.appendChild(document.createElement('div'));
      try {
        el.innerHTML = createHTML.call(p, '');
        if (trustedTypes[CP] === ovr) delete trustedTypes[CP];
        const proto = Element.prototype;
        const { insertAdjacentHTML } = proto;
        const d = Object.getOwnPropertyDescriptor(proto, 'innerHTML');
        const { set } = d;
        d.set = function (val) {
          set.call(this, createHTML.call(p, val));
        };
        Object.defineProperty(proto, 'innerHTML', d);
        proto.insertAdjacentHTML = function (pos, html) {
          return insertAdjacentHTML.call(this, pos, createHTML.call(p, html));
        };
      } catch (err) {
        createHTML = null;
      }
      el.remove();
    }
    return p;
  };
}

```
